version: '3.4'

services:

  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build: ./php-fpm
    ports:
      - ${PHP_PORT}:9000
    restart: always
    volumes:
      - ./${APP_FOLDER}:/var/www/html/${APP_NAME}/
      - ./php-fpm/conf.d/:/usr/local/etc/php/conf.d/
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx
    restart: always
    depends_on:
      - php
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./${APP_FOLDER}:/var/www/html/${APP_NAME}/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/:/var/log/nginx
    environment:
      APP_NAME: ${APP_NAME}
